# Generated by Django 4.2.8 on 2023-12-17 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="department",
            fields=[
                (
                    "dept_id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("dept_name", models.CharField(max_length=32)),
                ("address", models.CharField(max_length=32, unique=True)),
                ("phone_code", models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="T",
            fields=[
                (
                    "staff_id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("sex", models.CharField(blank=True, max_length=4)),
                ("date_of_birth", models.DateField(blank=True)),
                ("professional_ranks", models.CharField(blank=True, max_length=32)),
                ("salary", models.FloatField(blank=True)),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managementApp.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="student",
            fields=[
                (
                    "student_id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("sex", models.CharField(blank=True, max_length=4)),
                ("date_of_birth", models.DateField(blank=True)),
                ("native_place", models.CharField(blank=True, max_length=32)),
                (
                    "mobile_phone",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("average_gpa", models.FloatField(blank=True, null=True)),
                ("total_cerdict", models.FloatField(blank=True, null=True)),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managementApp.department",
                    ),
                ),
            ],
        ),
    ]
