# Generated by Django 4.2.8 on 2023-12-17 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="T",
            new_name="teacher",
        ),
    ]
