# Generated by Django 4.2.8 on 2023-12-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0003_alter_department_phone_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="course",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_name", models.CharField(max_length=32)),
                ("credit", models.IntegerField()),
                ("credit_hours", models.IntegerField()),
                (
                    "dept_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managementApp.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="open_course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester", models.CharField(max_length=32)),
                ("class_time", models.CharField(max_length=32)),
                (
                    "course_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managementApp.course",
                    ),
                ),
                (
                    "staff_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="managementApp.teacher",
                    ),
                ),
            ],
            options={
                "unique_together": {("semester", "course_id", "staff_id","class_time")},
            },
        ),
    ]
