# Generated by Django 4.2.8 on 2023-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0004_course_open_course"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="open_course",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="open_course",
            constraint=models.UniqueConstraint(
                fields=("semester", "course_id", "staff_id"),
                name="unique_constraint_name",
            ),
        ),
    ]
