# Generated by Django 4.2.8 on 2023-12-18 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0005_alter_open_course_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="open_course",
            name="unique_constraint_name",
        ),
        migrations.AlterUniqueTogether(
            name="open_course",
            unique_together={("semester", "course_id", "staff_id","class_time")},
        ),
    ]
