# Generated by Django 4.2.8 on 2023-12-22 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0008_student_user_id_teacher_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="normal_score_percent",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AddField(
            model_name="open_course",
            name="capacity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="open_course",
            name="used_capacity",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
