# Generated by Django 4.2.8 on 2023-12-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0008_student_user_id_teacher_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="mobile_phone",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
