# Generated by Django 4.2.8 on 2023-12-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "managementApp",
            "0009_course_normal_score_percent_open_course_capacity_and_more",
        ),
        ("managementApp", "0010_rename_total_cerdict_student_total_credit"),
    ]

    operations = []
