# Generated by Django 4.2.8 on 2023-12-25 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0011_merge_20231224_0012"),
    ]

    operations = [
        migrations.AddField(
            model_name="course_selection",
            name="open_course_id",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to="managementApp.open_course",
            ),
            preserve_default=False,
        ),
    ]
