# Generated by Django 4.2.8 on 2023-12-25 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0012_course_selection_open_course_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="open_course",
            unique_together={("semester", "course_id", "staff_id", "class_time")},
        ),
    ]
