# Generated by Django 4.2.8 on 2023-12-29 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0013_alter_open_course_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="course_request",
            fields=[
                (
                    "course_id",
                    models.CharField(
                        max_length=32, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("course_name", models.CharField(default="111", max_length=32)),
                ("credit", models.IntegerField()),
                ("credit_hours", models.IntegerField()),
                ("dept_id", models.CharField(max_length=32)),
                (
                    "normal_score_percent",
                    models.FloatField(
                        default=0.5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("staff_id", models.CharField(max_length=32)),
                ("status", models.IntegerField(default=0)),
            ],
        ),
    ]
