# Generated by Django 4.2.8 on 2023-12-29 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0013_alter_open_course_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="average_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
