# Generated by Django 4.2.8 on 2023-12-29 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0014_course_request"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course_request",
            name="dept_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="managementApp.department",
            ),
        ),
        migrations.AlterField(
            model_name="course_request",
            name="staff_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="managementApp.teacher"
            ),
        ),
    ]
