# Generated by Django 4.2.8 on 2023-12-30 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("managementApp", "0014_student_average_score"),
        ("managementApp", "0015_alter_course_request_dept_id_and_more"),
    ]

    operations = []
